# Both Test
all: test1 test2

# Test Targets
test1:
	g++ Ability.cpp Pokemon.cpp PokemonLeague.cpp test1.cpp -o test1.out

test2:
	g++ Ability.cpp Pokemon.cpp PokemonLeague.cpp test2.cpp -o test2.out

# Clean
clean:
	rm -f *.out